messages:
  potion-obtained: "&a‚ú® You've obtained a return potion! Use it to get back home."
  potion-used: "&6üè† Teleporting to your spawn point... ‚ú®"
  no-home-set: "&cYou don't have a spawn point set! Sleep in a bed or use /spawnpoint."
  not-enough-xp: "&cNot enough XP! Requires 8 levels of experience."
  portal-extract-success: "&a‚ú® You've extracted portal fluid! (-8 experience levels)"
  config-reloaded: "&aConfiguration reloaded!"
  no-permission: "&cYou don't have permission to use this command!"
achievements:
  home-return:
    title: "Home, Sweet Home!"
    description: "Use a return potion to get back home"
    icon: "ENDER_EYE" 
    frame: "task" 
    parent: "minecraft:adventure/root" 
  portal-extract:
    title: "Portal Master"
    description: "Extract portal fluid from an End portal"
    icon: "END_PORTAL_FRAME" 
    frame: "task"
    parent: "minecraft:adventure/root"
sounds:
  potion-obtain: "BLOCK_ENCHANTMENT_TABLE_USE"
  potion-use: "ENTITY_ENDERMAN_TELEPORT"
  portal-extract: "BLOCK_PORTAL_AMBIENT"
  achievement: "UI_TOAST_CHALLENGE_COMPLETE" 
settings:
  xp-cost: 8
  potion-name: "&d‚ú® Potion of Return"
  potion-lore:
    - "&7A magical potion that"
    - "&7teleports you back to your spawn point"
    - "&e‚ñ∂ Right-click to use"
